---
title: "EDS 223: week 1 lab"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
install.packages("sf") #vector data
install.packages("stars") #raster data
install.packages("tmap") #map making
install.packages("here") #file path management; defines location of data; file path starts in the project folder
```

```{r}
library(sf)
library(stars)
library(tmap)
library(here)

```

```{r}
## load data
# raster of global elevation

world_elevation <- read_stars(here("data","worldelevation.tif"))

# country boundaries
world_vector <- read_sf(here("data","worldvector.gpkg"))

# major cities
world_cities <- read_sf(here("data","worldcities.gpkg"))

```


```{r}
tm_shape(world_elevation) +
  tm_raster() +
tm_shape(world_vector) +  # all commands in tmap start with "tm_*"
#  tm_polygons() +  # adds filled polygon layer
  tm_borders() + # adds hollow polygon layer
  tm_shape(world_cities,is.master = TRUE) + # zoom to layer is the order in which the layers appear in the code. the first layer will determine the extent of the map. Can specify with "is.master"
  tm_dots() # adds point layer
```


```{r}
# can add bounding box either based on coordnates or a known layer

tm_shape(world_elevation, bbox = c(-15,35,45,65)) +
  tm_raster() +
tm_shape(world_vector) + 
  tm_borders()


tm_shape(world_elevation, bbox = world_cities) +
  tm_raster() +
tm_shape(world_vector) + 
  tm_borders()


```




```{r}

tm_shape(world_vector) +
  tm_polygons(col = "lightblue",
              border.col = "black",
              lwd = 0.5,  #line width
              lty = "dashed") #line type


```


```{r}
tm_shape(world_vector) +
  tm_borders(col = "red")

tm_shape(world_vector) +
   tm_fill(col = "lightblue")
```


```{r}
#create map of CO2 emissions
tm_shape(world_vector) +
  tm_fill("CO2_emissions")
```


```{r}
tm_shape(world_cities) +
  # tm_dots() + 
  #  tm_symbols()
  #  tm_bubbles()
  tm_squares()

```

```{r}
tm_shape(world_vector) +
  tm_polygons("life_expectancy",
              palette = c("yellow", "darkgreen"),
              title = "Life Expectancy (years)")

```

```{r}
# try viridis color palatte; handles color blindness considerations well
#install.packages("viridisLite")
library(viridisLite)

```


```{r}
tm_shape(world_vector) +
  tm_polygons("life_expectancy",
              palette = viridis(option = "plasma", 8),
              title = "Life Expectancy (years)")

```


```{r}

tm_shape(world_vector) +
  tm_polygons() +
  tm_shape(world_cities) +
  tm_symbols(size = "pop2020",
             legend.size.is.portrait = TRUE)

```

```{r}
tm_shape(world_vector) +
  tm_graticules() +
  tm_fill() #+
#  tm_grid() # minutes are default held in data object
#  tm_graticules()

```


```{r}
tm_shape(world_vector) +
  tm_fill() +
  tm_scale_bar() +
  tm_compass(position = c("left","top"))
```


```{r}
tmap_mode("view") # must be included in quarto doc to make an interactive map; uses Leaflet

tm_shape(world_vector) +
  tm_fill(col = "wb_income_region",
          palette = viridisLite::plasma(5),
          title = "Regional Income") +
  tm_layout(bg.color = "grey95",
            main.title = "Global income by country",
            frame = FALSE)

tmap_mode("plot") # creates a static map after a Leaflet interactive map is made. does not convert map made from prior code chunk.
```

```{r}
# Save figure

tmap_mode("plot")

map1 <- tm_shape(world_vector) +
  tm_fill(col = "wb_income_region",
          palette = viridisLite::plasma(5),
          title = "Regional Income") +
  tm_layout(bg.color = "grey95",
            main.title = "Global income by country",
            frame = FALSE)

tmap_save(map1, here("tmap-example1.png"))

```


